### ISSUE TITLE
Access denied while downloading dataset

### ISSUE THREAD

**Issue by hqy117** [X-LANCE/MSDWILD#3]
Hello, glad to see this awesome dataset.
I am trying to download it to the Linux server before using it.
Here is the command:
gdown https://drive.google.com/uc?id=1--rqm3AKjOI9q_iNgVUD_eC2u1m4OQHW

Normally, it works but I got an access denied problem this time:
<img width="548" alt="Screenshot 2024-01-19 at 11 58 06 PM" src="https://github.com/X-LANCE/MSDWILD/assets/75348213/4a3ca2cd-eeb9-4f12-b418-8a79ac6d77b1">

Can you help me with that or change the permission?

Thank you a lot.

**Comment by liutaocode** [comment]
Hello, we have not set any permissions for the link and it is currently publicly accessible. I have encountered this issue with gdown before as well; it may happen if the link gets banned by Google due to high traffic. 

I have two suggestions to address this issue:

1. Direct download through the website works fine.
2. Save the file to your own Google Drive first, then use the Google Drive client to download it.
 
The second method supports resuming downloads and is recommended if the internet connection is unreliable. 
I hope the above suggestions are helpful.
